// Generated by https://quicktype.io

export interface PokemonResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
    id: number;
    img: string;
}

export interface ResultPokes {
  name: string;
  url: string;
  id: string;
  img: string;
}
